//
// Generated file, do not edit! Created by opp_msgtool 6.2 from simu5g/apps/filetransfer_multicell/FilePacket.msg.
//

#ifndef __FILEPACKET_M_H
#define __FILEPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class FilePacket;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>simu5g/apps/filetransfer_multicell/FilePacket.msg:21</tt> by opp_msgtool.
 * <pre>
 * class FilePacket extends inet::FieldsChunk
 * {
 *     unsigned int nframes;
 *     unsigned int IDframe;
 *     simtime_t payloadTimestamp;
 *     unsigned int payloadSize;
 * }
 * </pre>
 */
class FilePacket : public ::inet::FieldsChunk
{
  protected:
    unsigned int nframes = 0;
    unsigned int IDframe = 0;
    omnetpp::simtime_t payloadTimestamp = SIMTIME_ZERO;
    unsigned int payloadSize = 0;

  private:
    void copy(const FilePacket& other);

  protected:
    bool operator==(const FilePacket&) = delete;

  public:
    FilePacket();
    FilePacket(const FilePacket& other);
    virtual ~FilePacket();
    FilePacket& operator=(const FilePacket& other);
    virtual FilePacket *dup() const override {return new FilePacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual unsigned int getNframes() const;
    virtual void setNframes(unsigned int nframes);

    virtual unsigned int getIDframe() const;
    virtual void setIDframe(unsigned int IDframe);

    virtual omnetpp::simtime_t getPayloadTimestamp() const;
    virtual void setPayloadTimestamp(omnetpp::simtime_t payloadTimestamp);

    virtual unsigned int getPayloadSize() const;
    virtual void setPayloadSize(unsigned int payloadSize);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FilePacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FilePacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline FilePacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<FilePacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __FILEPACKET_M_H

